from abc import ABC, abstractmethod
from typing import Any

from .models import Digest, DigestSection


class DigestTemplate(ABC):
    """Abstract template for rendering digests."""

    @abstractmethod
    def render(self, digest: Digest) -> str:
        """Render digest to output format."""
        ...


class EmailTemplate(DigestTemplate):
    """HTML email template for digests."""

    def render(self, digest: Digest) -> str:
        """Render digest as HTML email."""
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; }}
        .header {{ background: #2563eb; color: white; padding: 20px; }}
        .section {{ margin: 20px 0; padding: 15px; background: #f3f4f6; }}
        .section-title {{ color: #1f2937; font-size: 18px; margin-bottom: 10px; }}
        .item {{ margin: 10px 0; padding: 10px; background: white; border-left: 3px solid #2563eb; }}
        .item-title {{ font-weight: bold; }}
        .item-desc {{ color: #6b7280; font-size: 14px; }}
        .footer {{ text-align: center; color: #9ca3af; font-size: 12px; padding: 20px; }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{digest.title}</h1>
        <p>{digest.period_start.strftime('%B %d')} - {digest.period_end.strftime('%B %d, %Y')}</p>
    </div>

    <div class="section">
        <h2>Summary</h2>
        <p>{digest.summary}</p>
    </div>
"""

        # Render each section
        for section in DigestSection:
            items = digest.get_items_by_section(section)
            if items:
                html += self._render_section(section, items)

        html += """
    <div class="footer">
        <p>Generated by ASWA | <a href="#">Manage preferences</a></p>
    </div>
</body>
</html>
"""
        return html

    def _render_section(self, section: DigestSection, items: list) -> str:
        """Render a section."""
        section_titles = {
            DigestSection.NEW_RISKS: "New Risks",
            DigestSection.NEW_OPPORTUNITIES: "New Opportunities",
            DigestSection.KEY_ENTITIES: "Key Entities",
            DigestSection.TRENDS: "Trends",
            DigestSection.DOCUMENT_ACTIVITY: "Document Activity",
        }

        html = f"""
    <div class="section">
        <h2 class="section-title">{section_titles.get(section, section.value)}</h2>
"""
        for item in items:
            html += f"""
        <div class="item">
            <div class="item-title">{item.title}</div>
            <div class="item-desc">{item.description[:200]}...</div>
        </div>
"""
        html += "    </div>\n"
        return html


class SlackTemplate(DigestTemplate):
    """Slack message template for digests."""

    def render(self, digest: Digest) -> str:
        """Render digest as Slack mrkdwn."""
        blocks = []

        # Header
        blocks.append({
            "type": "header",
            "text": {"type": "plain_text", "text": digest.title}
        })

        blocks.append({
            "type": "section",
            "text": {"type": "mrkdwn", "text": digest.summary}
        })

        blocks.append({"type": "divider"})

        # Sections
        for section in DigestSection:
            items = digest.get_items_by_section(section)
            if items:
                blocks.extend(self._render_section(section, items))

        return {"blocks": blocks}

    def _render_section(self, section: DigestSection, items: list) -> list:
        """Render a section as Slack blocks."""
        section_emojis = {
            DigestSection.NEW_RISKS: ":warning:",
            DigestSection.NEW_OPPORTUNITIES: ":star:",
            DigestSection.KEY_ENTITIES: ":bust_in_silhouette:",
            DigestSection.TRENDS: ":chart_with_upwards_trend:",
        }

        blocks = []
        emoji = section_emojis.get(section, ":pushpin:")

        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*{emoji} {section.value.replace('_', ' ').title()}*"
            }
        })

        for item in items[:5]:
            blocks.append({
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"* *{item.title}*\n{item.description[:100]}..."
                }
            })

        return blocks


class MarkdownTemplate(DigestTemplate):
    """Markdown template for digests."""

    def render(self, digest: Digest) -> str:
        """Render digest as Markdown."""
        md = f"# {digest.title}\n\n"
        md += f"*{digest.period_start.strftime('%B %d')} - {digest.period_end.strftime('%B %d, %Y')}*\n\n"
        md += f"## Summary\n\n{digest.summary}\n\n"

        section_titles = {
            DigestSection.NEW_RISKS: "New Risks",
            DigestSection.NEW_OPPORTUNITIES: "New Opportunities",
            DigestSection.KEY_ENTITIES: "Key Entities",
            DigestSection.TRENDS: "Trends",
        }

        for section in DigestSection:
            items = digest.get_items_by_section(section)
            if items:
                md += f"## {section_titles.get(section, section.value)}\n\n"
                for item in items:
                    md += f"### {item.title}\n\n"
                    md += f"{item.description}\n\n"

        return md
