from typing import Any
from pydantic import BaseModel
import structlog

from aswa_integrations.jira.project_config import JiraProjectConfigResponse

logger = structlog.get_logger()


class MappedIssueData(BaseModel):
    """Mapped issue data ready for Jira."""
    summary: str
    description: str
    issue_type: str
    priority: str
    labels: list[str]
    custom_fields: dict[str, Any] = {}


class JiraFieldMapper:
    """Maps ASWA insights to Jira issue fields."""

    def __init__(self, config: JiraProjectConfigResponse):
        """Initialize field mapper.

        Args:
            config: Project configuration
        """
        self.config = config

    def map_insight_to_issue(
        self,
        insight: dict[str, Any],
    ) -> MappedIssueData:
        """Map an ASWA insight to Jira issue fields.

        Args:
            insight: ASWA insight data

        Returns:
            Mapped issue data
        """
        insight_type = insight.get("type", "unknown")
        severity = insight.get("severity", "medium")

        # Determine issue type
        if insight_type == "risk":
            issue_type = self.config.risk_issue_type
        elif insight_type == "opportunity":
            issue_type = self.config.opportunity_issue_type
        else:
            issue_type = self.config.default_issue_type

        # Map priority
        priority = self.config.priority_mapping.get(
            severity,
            "Medium",
        )

        # Build labels
        labels = list(self.config.auto_labels)
        if self.config.include_severity_label:
            labels.append(f"severity:{severity}")
        if self.config.include_type_label:
            labels.append(f"type:{insight_type}")

        # Build description
        description = self._build_description(insight)

        # Map custom fields
        custom_fields = self._map_custom_fields(insight)

        return MappedIssueData(
            summary=self._build_summary(insight),
            description=description,
            issue_type=issue_type,
            priority=priority,
            labels=labels,
            custom_fields=custom_fields,
        )

    def _build_summary(
        self,
        insight: dict[str, Any],
    ) -> str:
        """Build issue summary from insight.

        Args:
            insight: ASWA insight data

        Returns:
            Issue summary
        """
        title = insight.get("title", "Untitled Insight")

        # Prefix with type indicator
        insight_type = insight.get("type", "insight")
        prefix = {
            "risk": "[RISK]",
            "opportunity": "[OPP]",
            "entity": "[ENTITY]",
            "trend": "[TREND]",
        }.get(insight_type, "[INSIGHT]")

        return f"{prefix} {title}"

    def _build_description(
        self,
        insight: dict[str, Any],
    ) -> str:
        """Build issue description from insight.

        Args:
            insight: ASWA insight data

        Returns:
            Formatted description
        """
        lines = []

        # Main description
        description = insight.get("description", "")
        if description:
            lines.append(description)
            lines.append("")

        # Confidence
        confidence = insight.get("confidence", 0)
        lines.append(f"*Confidence:* {confidence:.0%}")

        # Severity
        severity = insight.get("severity")
        if severity:
            lines.append(f"*Severity:* {severity.title()}")

        # Source document
        doc_name = insight.get("document_name")
        if doc_name:
            lines.append(f"*Source:* {doc_name}")

        # Evidence/excerpt
        evidence = insight.get("evidence") or insight.get("excerpt")
        if evidence:
            lines.append("")
            lines.append("h3. Evidence")
            lines.append("{quote}")
            lines.append(evidence)
            lines.append("{quote}")

        # ASWA reference
        lines.append("")
        lines.append("----")
        insight_id = insight.get("id", "unknown")
        lines.append(f"_Generated by ASWA | Insight ID: {insight_id}_")

        return "\n".join(lines)

    def _map_custom_fields(
        self,
        insight: dict[str, Any],
    ) -> dict[str, Any]:
        """Map insight fields to Jira custom fields.

        Args:
            insight: ASWA insight data

        Returns:
            Custom field values
        """
        custom_fields = {}

        for insight_field, jira_field in self.config.custom_field_mappings.items():
            if insight_field in insight:
                custom_fields[jira_field] = insight[insight_field]

        return custom_fields

    def map_status_to_transition(
        self,
        insight_status: str,
        available_transitions: list[dict],
    ) -> str | None:
        """Map ASWA insight status to Jira transition.

        Args:
            insight_status: ASWA insight status
            available_transitions: List of available Jira transitions

        Returns:
            Transition ID or None
        """
        # Default status mappings
        status_map = {
            "new": ["To Do", "Open", "Backlog"],
            "in_progress": ["In Progress", "In Development"],
            "resolved": ["Done", "Resolved", "Closed"],
            "dismissed": ["Won't Do", "Rejected", "Closed"],
        }

        target_statuses = status_map.get(insight_status, [])

        for transition in available_transitions:
            if transition.get("name") in target_statuses:
                return transition.get("id")

        return None
