apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app.kubernetes.io/name: otel-collector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aswa-otel-collector
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app.kubernetes.io/name: jaeger
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aswa-jaeger
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: admin-http
      interval: 15s
      path: /metrics
